# Generated by Django 5.2.8 on 2025-11-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='interest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
