# Generated by Django 5.2.8 on 2025-12-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('level', models.CharField(default='Beginner', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option_index',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.module'),
        ),
    ]
