# Generated by Django 5.2.8 on 2025-12-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_module_alter_quizquestion_correct_option_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='timestamp',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='module_name',
        ),
        migrations.AddField(
            model_name='examresult',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='status',
            field=models.CharField(default='Lulus', max_length=20),
            preserve_default=False,
        ),
    ]
