# Generated by Django 5.2.8 on 2025-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_timestamp_examresult_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True, help_text='Fill the material learning content here.', null=True),
        ),
    ]
