# Generated by Django 5.2.8 on 2025-12-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_module_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('Cyber Security', 'Cyber Security'), ('IoT', 'Internet of Things'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
