# Generated by Django 5.2.8 on 2025-12-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=1, help_text='Module sequences (1, 2, 3...)'),
        ),
    ]
